pages:
  image: node:latest
  stage: deploy
  script:
    - npm install --progress=false
    - npm run app:build
    - rm -rf public
    - mv dist public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - main
