pages:
  image: node:latest
  stage: deploy
  script:
    - yarn install
    - yarn run app:build
    - yarn run docs:build
    - rm -rf public
    - mv dist public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - main
