jsxBracketSameLine: true
vueIndentScriptAndStyle: false
tabWidth: 2
arrowParens: "avoid"
bracketSpacing: true
bracketSameLine: true
trailingComma: "none"
semi: false
singleQuote: false
htmlWhitespaceSensitivity: "ignore" # prevent dangling right angle bracket
